unique_ids:
  assets: {}
  forms: {}
  modules:
    ColumnShufflerForm: IUE2DLN7D2A25IJXCEHAZQXILFGNIKYB
    CompareCSVForm: YHCPE2QWIDAXDHNPHOZMLN5WJITMY4VK
    ExcelMatcherForm: QOTRFJ5GP2ZTWCQOERZW7ED7NFYXRRRS
    HoldingTaxForm: 5JRMR2T6RSVJTGW5L2P7L3ALCWVEXX6U
    LoginForm: RTUZBJIS3NX3RRVJS7JBJICJ2MKVVT37
    MainForm: GCW25H7FMWOSBMRAMSDJUFADH2IOQ6KI
    PDFtoExcelForm: CZSIMQLKCAH67UEW5L2ATC2HUEZYKJ7Z
    _anvil_designer.ColumnShufflerFormTemplate: DWEYVJVJZNVH2DQYKNV37IJKLSVZ7EYH
    _anvil_designer.CompareCSVFormTemplate: TORWKSU4YYBMK26ZYLAHXSS5VMEZDNTM
    _anvil_designer.ExcelMatcherFormTemplate: OOI3WZ6VEALC7WMJDAHO4IDL3HXLEJVO
    _anvil_designer.HoldingTaxFormTemplate: UHNDBTQLAMWFK5E3ESYV37Q2POZDP67L
    _anvil_designer.LoginFormTemplate: 7WLL7ML6LAV73JU34TSNGFN2PE2NTOJE
    _anvil_designer.MainFormTemplate: EVIIHYZRGDKB5VVNVCNUEQ24EVPHYZZ6
    _anvil_designer.PDFtoExcelFormTemplate: HT3RU5OGJTG3IA3FROVV3JJHKQBYKJ3V
  scripts: {}
  server_modules:
    auth_service: W4QXJR3DCD6MR56WQ5PARBCZ2T22WUZF
    file_service: 2KS3FPYPEWSCBXVZ46TIWDXPBE5UXNWK
